// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/NavBar";
import { Geist, Geist_Mono, Nunito } from "next/font/google";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--nunito",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable}`}
      // 👆 put font variables on <html>
    >
      <body className="antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
